// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

float ScreenResolutionX;
float ScreenResolutionY;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float x = id.x / ScreenResolutionX;
    float y = id.y / ScreenResolutionY;

    Result[id.xy] = float4(x, y, 0.0, 0.0);
}
